apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa
  namespace: argocd
spec:
  project: qa
  source:
    repoURL: https://github.com/aaronbushell1984/stab-qa-poc
    targetRevision: HEAD
    path: qa
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
