apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-paradox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: qa
  source:
    path: helm
    repoURL: https://github.com/aaronbushell1984/devops-paradox.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
#        ingress:
#          host: devopsparadox.com
      version: v3
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true