apiVersion: v1
kind: Service
metadata:
  name: react-poc
spec:
  selector:
    app.kubernetes.io/name: react-poc
  ports:
    - port: 1337 # service port inside cluster
      targetPort: 1337 # app bind port