apiVersion: v1
kind: Service
metadata:
  name: react-poc
spec:
  selector:
    app.kubernetes.io/name: react-poc
  ports:
    - port: 80 # service port inside cluster
      targetPort: 80 # app bind port