apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: qa
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/aaronbushell1984/stab-qa-poc
  password: ${GITHUB_TOKEN}
  username: aaronbushell1984